name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  clippy:
    if: github.actor != 'github-actions[bot]'
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust clippy
        run: cargo clippy -- -Dclippy::all -D warnings

  rust-fmt:
    if: github.actor != 'github-actions[bot]'
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust fmt
        run: cargo fmt --check

  test:
    if: github.actor != 'github-actions[bot]'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust test
        run: cargo test --workspace