name: Build and tag Rust project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: ${{ github.actor }} authorized build and tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --locked 
      - name: Run tests
        run: cargo test
      - name: Bump and Tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
        id: bump_version
