name: tag-and-version

on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
  workflow_dispatch:

jobs:
  tag:
    if: github.actor != 'github-actions[bot]'
    name: ${{ github.actor }} authorized build and tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Generate new version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: ${{ env.PACKAGE_VERSION }}
          DRY_RUN: true
        id: bump_version

      - name: Set package version
        run: |
          sed -i".bak" '/^version =/ s/="[^"]*"$/="'"${{ steps.bump_version.outputs.new_tag }}"'"/' Cargo.toml

          if [[ $? != 0 ]]; then
              echo "ERROR: Failed to update the version number in Cargo.toml" >&2
              exit 1
          else
              echo "Successfully updated the version number in Cargo.toml to ${{ steps.bump_version.outputs.new_tag }}"
          fi

      - name: Commit
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "chore: bump version to ${{ steps.bump_version.outputs.new_tag }}"
          git tag v"${{ steps.bump_version.outputs.new_tag }}"
          git push origin ${{ github.ref }} --follow-tags
